### ISSUE TITLE
Minimal helm startup hanging. Originally thought to be related to transformation url's.

### ISSUE THREAD

**Issue by svidrascu** [Alfresco/acs-deployment#167]
Original issue title: "There is no way to remove the transformation url's from the repo config".

The urls for the transformation services still end up in the properties file causing acs to try to connect to the transformers which severely slows down startup.

I tried disabling transformations using 

        -Dlocal.transform.service.enabled=false
        -Dtransform.service.enabled=false

and setting the appropriate replicaCounts to 0
  imagemagick:
    replicaCount: 0
  libreoffice:
    replicaCount: 0
  pdfrenderer:
    replicaCount: 0
  tika:
    replicaCount: 0
  transformrouter:
    replicaCount: 0

However, because the url's to the transformations still endup in alfresco.properties, it seems ACS still tries to connect to them.

**Comment by alandavis** [comment]
I think the above comment about the existence (rather than the setting) of local.transform.service.enabled and transform.service.enabled properties is probably wrong.

There is something else happening such as waiting for a non existant message queue to respond.

There are currently three possible types of transformer.
* T-Engines accessed via the Transform Service using messages and shared file store.
* Local transforms within the repo JVM - if a external process (such as LibreOffice) is incorrectly configure this can sometimes cause a delay regardless of these property values.
* Local transforms that happen to use the same T-Engines as the as the Transform Service but are connected directly via http. In this case they should be controlled by local.transform.service.enabled as the design of the T-Engines was that it did not matter if the T-Engine of repo came up first or even if they go down and come back up.

**Comment by alandavis** [comment]
Following our conversation earlier, I think it may be worth you investigating the active message queue option and possibly any pod start up dependencies.

The reason is that I have just tried a BAT development environment (latest master branch version of all the repo side source projects), with only postgres and amq docker images pre-started. I also set the following a-g.p. So it is basically what you were trying to do in helm: no Transform Service (option 1 above ACS 6.1 style) or no directly connected T-Engines (option 3 above ACS 6.0 style), leaving just the 5.2 style transformers (option 2 above ACS 5.2 style). Note the ImageMagic, PDF.Renderer and LibreOffice transforms will not work as the external processes have not been installed (just like you). 
~~~
local.transform.service.enabled=false
transform.service.enabled=false
~~~
The attached alfresco.txt (extension changed) shows the start up on my laptop in less than a minute. The last entry is me logging into Share about 30 seconds later.
[alfresco.txt](https://github.com/Alfresco/acs-deployment/files/3004215/alfresco.txt)

In the enterprise edition, the a-g.p by default include the following, so the log also includes attempts to contact the missing T-Engines (option 3 - Search for "is not available for transformations"). You will note there is no delay and an attempt is made to contact them regardless of the local.transform.service.enabled setting.
~~~
jodconverter.url=http://libreoffice:8090/
img.url=http://imagemagick:8090/
tika.url=http://tika:8090/
sfs.url=http://shared-file-store:8099/
~~~
If you set the a-g.p to the following, you are back to ACS 5.2 style and you will see ERRORS in the log (not in the previous log) about failing to access ImageMagick and officehome not being set. Again the repo starts 2p in just under a minute. 
[alfresco52.txt](https://github.com/Alfresco/acs-deployment/files/3004368/alfresco52.txt)
~~~
jodconverter.url=
img.url=
tika.url=
sfs.url=
~~~

**Comment by alandavis** [comment]
The following is the what is being attempted in helm: https://github.com/Alfresco/alfresco-dbp-deployment/blob/master/charts/incubator/alfresco-dbp/minimal-values.yaml

**Comment by alandavis** [comment]
Raised https://issues.alfresco.com/jira/browse/REPO-4394 to investigate.
