### ISSUE TITLE
You cannot have different persistence claims for repo and filestore

### ISSUE THREAD

**Issue by svidrascu** [Alfresco/acs-deployment#168]
The same value persistence.existingClaim is being used for both repo and filestore so you cannot use different storage locations for them.

**Comment by alandavis** [comment]
Stefan, we are looking for your architectural input on this. One possible reason that we do not have separate claims is that we had the intension of making the share file store (SFS) use the same store, so that we could provide a shortcut so that there was no need to actually do a copy at all in a future iteration of the SFS and repo.

**Comment by alandavis** [comment]
Raised https://issues.alfresco.com/jira/browse/REPO-4393
