### ISSUE TITLE
Can't pull transform-router 1.2.0-RC1 from quay.io

### ISSUE THREAD

**Issue by ZlobnyiSerg** [Alfresco/acs-deployment#316]
Docker-compose up finished with error:
```
Pulling transform-router (quay.io/alfresco/alfresco-transform-router:1.2.0-RC1)...
ERROR: unauthorized: access to the requested resource is not authorized
```

**Comment by jvocat** [comment]
I've just had the same problem but I figured it out.

If you're trying to run the community edition you're probably not using the appropriate project. 
There is another one on github named Alfresco / acs-community-deployment.

Otherwise I guess you need to authenticate to quay.io repositories before running docker-compose.

**Comment by montgolfiere** [comment]
Yes, https://github.com/jvocat is correct.

See also https://github.com/Alfresco/acs-deployment/blob/master/README.md#other-information
